; PlatformIO Project Configuration
; ESP32 Multitool (Flipper-like) - Proyecto Integrados
; Target: M5Stack Cardputer (ESP32-S3FN8)

[platformio]
default_envs = cardputer
src_dir = src

[env:cardputer]
platform = espressif32
board = m5stack-stamps3
framework = arduino
monitor_speed = 115200
upload_speed = 921600

board_build.partitions = huge_app.csv
board_build.psram_type = opi
build_flags =
    -D CORE_DEBUG_LEVEL=3
    -D BOARD_HAS_PSRAM
    -mfix-esp32-psram-cache-issue

lib_deps =
    m5stack/M5Cardputer@^1.0.3
    m5stack/M5GFX@^0.1.13
    m5stack/M5Unified@^0.1.16
    miguelbalboa/MFRC522@^1.4.11
    crankyoldgit/IRremoteESP8266@^2.8.6
    bblanchon/ArduinoJson@^7.0.4

monitor_filters =
    esp32_exception_decoder
    default
